// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojruembaqcigqfjufpwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qcnVlbWJhcWNpZ3FmanVmcHdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTgyOTgsImV4cCI6MjA2NTQ3NDI5OH0.4sZplahjyMRcK9o4RrngRCp3NM2mNAD-fxOb1-Ow-Qw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  global: {
    headers: {
      'x-client-info': 'vibecatcher-app@1.0.0',
    },
  },
});